#!/bin/bash

set -e

version=`git describe --tags`
echo $version

here=$(dirname "$0")
cd $here/../dist

sftp -oBatchMode=no -b - samad@gamecredits.org << !
   cd electrum-downloads
   mkdir $version
   cd $version
   mput *
   bye
!
